version: "2"

services:

    backend:
      build:
        context: .
        dockerfile: ./backend/Dockerfile
      volumes:
        # Frontend
        - ./frontend/index.html:/app/index.html:ro
        - ./frontend/show_score.html:/app/templates/show_score.html:ro
        - ./frontend/share_score.html:/app/templates/share_score.html:ro
        - ./frontend/static/:/app/static/:rw
        # App files and config
        - ./backend/config/uwsgi.ini:/app/uwsgi.ini:ro
        - ./backend/config/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
        - ./backend/app/main.py:/app/main.py:ro
        # xmlLib
        - ./face_rating/haarcascade_frontalface_default.xml:/opt/opencv/data/haarcascades/haarcascade_frontalface_default.xml:ro
        # Library
        - ./backend:/usr/local/lib/python3.5/site-packages/backend:ro
        - ./face_rating:/usr/local/lib/python3.5/site-packages/face_rating:ro
        # Data
        - ./data/scoring_model.h5:/model/scoring_model.h5
        # Runners
        - ./backend/runners/:/app/runners:ro
        # Linters and Tests
        - ./backend/tests/:/app/tests:ro
        - ./backend/.flake8:/app/.flake8:ro
        - ./backend/.coveragerc:/app/.coveragerc:ro
        # Entrypoint
        - ./backend/config/entrypoint.sh:/entrypoint.sh:ro
      # env_file:
      #   - .env
      ports:
        - 80:8080
